import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Content from "@/views/SectionContent";
import Features from "@/views/SectionFeatures";
import Gallery from "@/views/SectionGallery";
import Hero from "@/views/SectionHero";
import Newsletter from "@/views/SectionNewsLetter";
import Partners from "@/views/SectionPartners";
import Testimonials from "@/views/SectionTestimonials";
import Head from "next/head";
{
  /*
import { Inter } from "next/font/google";


    const inter = Inter({ subsets: ["latin"] });

        <main className={`${styles.main} ${inter.className}`}>
  */
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Figma Land</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Features />
        <Content />
        <Gallery />
        <Partners />
        <Testimonials />
        <Newsletter />
        <Footer />
      </main>
    </>
  );
}
